name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
      - /docs 
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - /docs
    
jobs:
  buildAndTest:
    name: Build and Test

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Create living Doc
      run: |
        dotnet tool run livingdoc feature-folder .\SpecFlowCalculator.Specs\ -t .\SpecFlowCalculator.Specs\bin\Debug\net6.0\TestExecution.json
    
    - name: Copy report 
      run: |
        Copy-Item LivingDoc.html /docs/LivingDoc.html
    
    - name: Commit report
      run: |
        git config --global user.name 'GitHub Bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git commit -am "Test Results report"
        git pull
        git push  
    

